// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: internal/proto/marketdata.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimulationType int32

const (
	SimulationType_STATISTICAL_SIMILARITY SimulationType = 0
	SimulationType_MONTE_CARLO            SimulationType = 1
	SimulationType_BROWNIAN_MOTION        SimulationType = 2
	SimulationType_MEAN_REVERSION         SimulationType = 3
	SimulationType_TREND_FOLLOWING        SimulationType = 4
)

// Enum value maps for SimulationType.
var (
	SimulationType_name = map[int32]string{
		0: "STATISTICAL_SIMILARITY",
		1: "MONTE_CARLO",
		2: "BROWNIAN_MOTION",
		3: "MEAN_REVERSION",
		4: "TREND_FOLLOWING",
	}
	SimulationType_value = map[string]int32{
		"STATISTICAL_SIMILARITY": 0,
		"MONTE_CARLO":            1,
		"BROWNIAN_MOTION":        2,
		"MEAN_REVERSION":         3,
		"TREND_FOLLOWING":        4,
	}
)

func (x SimulationType) Enum() *SimulationType {
	p := new(SimulationType)
	*p = x
	return p
}

func (x SimulationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulationType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_marketdata_proto_enumTypes[0].Descriptor()
}

func (SimulationType) Type() protoreflect.EnumType {
	return &file_internal_proto_marketdata_proto_enumTypes[0]
}

func (x SimulationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulationType.Descriptor instead.
func (SimulationType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{0}
}

type ScenarioType int32

const (
	ScenarioType_RALLY            ScenarioType = 0
	ScenarioType_CRASH            ScenarioType = 1
	ScenarioType_DIVERGENCE       ScenarioType = 2
	ScenarioType_MEAN_REVERTING   ScenarioType = 3
	ScenarioType_VOLATILITY_SPIKE ScenarioType = 4
	ScenarioType_CONSOLIDATION    ScenarioType = 5
)

// Enum value maps for ScenarioType.
var (
	ScenarioType_name = map[int32]string{
		0: "RALLY",
		1: "CRASH",
		2: "DIVERGENCE",
		3: "MEAN_REVERTING",
		4: "VOLATILITY_SPIKE",
		5: "CONSOLIDATION",
	}
	ScenarioType_value = map[string]int32{
		"RALLY":            0,
		"CRASH":            1,
		"DIVERGENCE":       2,
		"MEAN_REVERTING":   3,
		"VOLATILITY_SPIKE": 4,
		"CONSOLIDATION":    5,
	}
)

func (x ScenarioType) Enum() *ScenarioType {
	p := new(ScenarioType)
	*p = x
	return p
}

func (x ScenarioType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScenarioType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_marketdata_proto_enumTypes[1].Descriptor()
}

func (ScenarioType) Type() protoreflect.EnumType {
	return &file_internal_proto_marketdata_proto_enumTypes[1]
}

func (x ScenarioType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScenarioType.Descriptor instead.
func (ScenarioType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{1}
}

type HealthStatus int32

const (
	HealthStatus_UNKNOWN         HealthStatus = 0
	HealthStatus_SERVING         HealthStatus = 1
	HealthStatus_NOT_SERVING     HealthStatus = 2
	HealthStatus_SERVICE_UNKNOWN HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_marketdata_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_marketdata_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{2}
}

type GetPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRequest) Reset() {
	*x = GetPriceRequest{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRequest) ProtoMessage() {}

func (x *GetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetPriceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *GetPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceResponse) Reset() {
	*x = GetPriceResponse{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceResponse) ProtoMessage() {}

func (x *GetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceResponse.ProtoReflect.Descriptor instead.
func (*GetPriceResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *GetPriceResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPriceResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetPriceResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetPriceResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type StreamPricesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbols          []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	UpdateIntervalMs int32                  `protobuf:"varint,2,opt,name=update_interval_ms,json=updateIntervalMs,proto3" json:"update_interval_ms,omitempty"` // milliseconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamPricesRequest) Reset() {
	*x = StreamPricesRequest{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPricesRequest) ProtoMessage() {}

func (x *StreamPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPricesRequest.ProtoReflect.Descriptor instead.
func (*StreamPricesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *StreamPricesRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *StreamPricesRequest) GetUpdateIntervalMs() int32 {
	if x != nil {
		return x.UpdateIntervalMs
	}
	return 0
}

type PriceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume        float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	ChangeInfo    *PriceChangeInfo       `protobuf:"bytes,6,opt,name=change_info,json=changeInfo,proto3" json:"change_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdate) ProtoMessage() {}

func (x *PriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdate.ProtoReflect.Descriptor instead.
func (*PriceUpdate) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *PriceUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceUpdate) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceUpdate) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PriceUpdate) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PriceUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PriceUpdate) GetChangeInfo() *PriceChangeInfo {
	if x != nil {
		return x.ChangeInfo
	}
	return nil
}

type PriceChangeInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChangeAmount     float64                `protobuf:"fixed64,1,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	ChangePercentage float64                `protobuf:"fixed64,2,opt,name=change_percentage,json=changePercentage,proto3" json:"change_percentage,omitempty"`
	DailyHigh        float64                `protobuf:"fixed64,3,opt,name=daily_high,json=dailyHigh,proto3" json:"daily_high,omitempty"`
	DailyLow         float64                `protobuf:"fixed64,4,opt,name=daily_low,json=dailyLow,proto3" json:"daily_low,omitempty"`
	DailyVolume      float64                `protobuf:"fixed64,5,opt,name=daily_volume,json=dailyVolume,proto3" json:"daily_volume,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PriceChangeInfo) Reset() {
	*x = PriceChangeInfo{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceChangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceChangeInfo) ProtoMessage() {}

func (x *PriceChangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceChangeInfo.ProtoReflect.Descriptor instead.
func (*PriceChangeInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{4}
}

func (x *PriceChangeInfo) GetChangeAmount() float64 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

func (x *PriceChangeInfo) GetChangePercentage() float64 {
	if x != nil {
		return x.ChangePercentage
	}
	return 0
}

func (x *PriceChangeInfo) GetDailyHigh() float64 {
	if x != nil {
		return x.DailyHigh
	}
	return 0
}

func (x *PriceChangeInfo) GetDailyLow() float64 {
	if x != nil {
		return x.DailyLow
	}
	return 0
}

func (x *PriceChangeInfo) GetDailyVolume() float64 {
	if x != nil {
		return x.DailyVolume
	}
	return 0
}

type SimulationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Symbol         string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StartTime      *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SimulationType SimulationType         `protobuf:"varint,4,opt,name=simulation_type,json=simulationType,proto3,enum=marketdata.SimulationType" json:"simulation_type,omitempty"`
	Parameters     *SimulationParameters  `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulationRequest) Reset() {
	*x = SimulationRequest{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRequest) ProtoMessage() {}

func (x *SimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRequest.ProtoReflect.Descriptor instead.
func (*SimulationRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{5}
}

func (x *SimulationRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SimulationRequest) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SimulationRequest) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SimulationRequest) GetSimulationType() SimulationType {
	if x != nil {
		return x.SimulationType
	}
	return SimulationType_STATISTICAL_SIMILARITY
}

func (x *SimulationRequest) GetParameters() *SimulationParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type SimulationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	HistoricalData    []*PricePoint          `protobuf:"bytes,2,rep,name=historical_data,json=historicalData,proto3" json:"historical_data,omitempty"`
	SimulatedData     []*PricePoint          `protobuf:"bytes,3,rep,name=simulated_data,json=simulatedData,proto3" json:"simulated_data,omitempty"`
	SimilarityMetrics *StatisticalMetrics    `protobuf:"bytes,4,opt,name=similarity_metrics,json=similarityMetrics,proto3" json:"similarity_metrics,omitempty"`
	SimulationId      string                 `protobuf:"bytes,5,opt,name=simulation_id,json=simulationId,proto3" json:"simulation_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SimulationResponse) Reset() {
	*x = SimulationResponse{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResponse) ProtoMessage() {}

func (x *SimulationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResponse.ProtoReflect.Descriptor instead.
func (*SimulationResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{6}
}

func (x *SimulationResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SimulationResponse) GetHistoricalData() []*PricePoint {
	if x != nil {
		return x.HistoricalData
	}
	return nil
}

func (x *SimulationResponse) GetSimulatedData() []*PricePoint {
	if x != nil {
		return x.SimulatedData
	}
	return nil
}

func (x *SimulationResponse) GetSimilarityMetrics() *StatisticalMetrics {
	if x != nil {
		return x.SimilarityMetrics
	}
	return nil
}

func (x *SimulationResponse) GetSimulationId() string {
	if x != nil {
		return x.SimulationId
	}
	return ""
}

type ScenarioRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ScenarioType    ScenarioType           `protobuf:"varint,2,opt,name=scenario_type,json=scenarioType,proto3,enum=marketdata.ScenarioType" json:"scenario_type,omitempty"`
	Parameters      *ScenarioParameters    `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	StartTime       *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScenarioRequest) Reset() {
	*x = ScenarioRequest{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioRequest) ProtoMessage() {}

func (x *ScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioRequest.ProtoReflect.Descriptor instead.
func (*ScenarioRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{7}
}

func (x *ScenarioRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ScenarioRequest) GetScenarioType() ScenarioType {
	if x != nil {
		return x.ScenarioType
	}
	return ScenarioType_RALLY
}

func (x *ScenarioRequest) GetParameters() *ScenarioParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ScenarioRequest) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ScenarioRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type PricePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricePoint) Reset() {
	*x = PricePoint{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricePoint) ProtoMessage() {}

func (x *PricePoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricePoint.ProtoReflect.Descriptor instead.
func (*PricePoint) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{8}
}

func (x *PricePoint) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PricePoint) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *PricePoint) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *PricePoint) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PricePoint) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *PricePoint) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type StatisticalMetrics struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	CorrelationCoefficient       float64                `protobuf:"fixed64,1,opt,name=correlation_coefficient,json=correlationCoefficient,proto3" json:"correlation_coefficient,omitempty"`
	VolatilitySimilarity         float64                `protobuf:"fixed64,2,opt,name=volatility_similarity,json=volatilitySimilarity,proto3" json:"volatility_similarity,omitempty"`
	ReturnDistributionSimilarity float64                `protobuf:"fixed64,3,opt,name=return_distribution_similarity,json=returnDistributionSimilarity,proto3" json:"return_distribution_similarity,omitempty"`
	TrendSimilarity              float64                `protobuf:"fixed64,4,opt,name=trend_similarity,json=trendSimilarity,proto3" json:"trend_similarity,omitempty"`
	ConfidenceScore              float64                `protobuf:"fixed64,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *StatisticalMetrics) Reset() {
	*x = StatisticalMetrics{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticalMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticalMetrics) ProtoMessage() {}

func (x *StatisticalMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticalMetrics.ProtoReflect.Descriptor instead.
func (*StatisticalMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{9}
}

func (x *StatisticalMetrics) GetCorrelationCoefficient() float64 {
	if x != nil {
		return x.CorrelationCoefficient
	}
	return 0
}

func (x *StatisticalMetrics) GetVolatilitySimilarity() float64 {
	if x != nil {
		return x.VolatilitySimilarity
	}
	return 0
}

func (x *StatisticalMetrics) GetReturnDistributionSimilarity() float64 {
	if x != nil {
		return x.ReturnDistributionSimilarity
	}
	return 0
}

func (x *StatisticalMetrics) GetTrendSimilarity() float64 {
	if x != nil {
		return x.TrendSimilarity
	}
	return 0
}

func (x *StatisticalMetrics) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

type SimulationParameters struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VolatilityFactor float64                `protobuf:"fixed64,1,opt,name=volatility_factor,json=volatilityFactor,proto3" json:"volatility_factor,omitempty"`
	TrendFactor      float64                `protobuf:"fixed64,2,opt,name=trend_factor,json=trendFactor,proto3" json:"trend_factor,omitempty"`
	DataPoints       int32                  `protobuf:"varint,3,opt,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	IncludeNoise     bool                   `protobuf:"varint,4,opt,name=include_noise,json=includeNoise,proto3" json:"include_noise,omitempty"`
	NoiseLevel       float64                `protobuf:"fixed64,5,opt,name=noise_level,json=noiseLevel,proto3" json:"noise_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SimulationParameters) Reset() {
	*x = SimulationParameters{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationParameters) ProtoMessage() {}

func (x *SimulationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationParameters.ProtoReflect.Descriptor instead.
func (*SimulationParameters) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{10}
}

func (x *SimulationParameters) GetVolatilityFactor() float64 {
	if x != nil {
		return x.VolatilityFactor
	}
	return 0
}

func (x *SimulationParameters) GetTrendFactor() float64 {
	if x != nil {
		return x.TrendFactor
	}
	return 0
}

func (x *SimulationParameters) GetDataPoints() int32 {
	if x != nil {
		return x.DataPoints
	}
	return 0
}

func (x *SimulationParameters) GetIncludeNoise() bool {
	if x != nil {
		return x.IncludeNoise
	}
	return false
}

func (x *SimulationParameters) GetNoiseLevel() float64 {
	if x != nil {
		return x.NoiseLevel
	}
	return 0
}

type ScenarioParameters struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Intensity         float64                `protobuf:"fixed64,1,opt,name=intensity,proto3" json:"intensity,omitempty"`                                         // 0.1 to 2.0
	DurationFactor    float64                `protobuf:"fixed64,2,opt,name=duration_factor,json=durationFactor,proto3" json:"duration_factor,omitempty"`         // How long the scenario lasts
	RecoveryFactor    float64                `protobuf:"fixed64,3,opt,name=recovery_factor,json=recoveryFactor,proto3" json:"recovery_factor,omitempty"`         // How quickly it recovers
	GradualTransition bool                   `protobuf:"varint,4,opt,name=gradual_transition,json=gradualTransition,proto3" json:"gradual_transition,omitempty"` // Gradual vs sudden onset
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScenarioParameters) Reset() {
	*x = ScenarioParameters{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioParameters) ProtoMessage() {}

func (x *ScenarioParameters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioParameters.ProtoReflect.Descriptor instead.
func (*ScenarioParameters) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{11}
}

func (x *ScenarioParameters) GetIntensity() float64 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *ScenarioParameters) GetDurationFactor() float64 {
	if x != nil {
		return x.DurationFactor
	}
	return 0
}

func (x *ScenarioParameters) GetRecoveryFactor() float64 {
	if x != nil {
		return x.RecoveryFactor
	}
	return 0
}

func (x *ScenarioParameters) GetGradualTransition() bool {
	if x != nil {
		return x.GradualTransition
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=marketdata.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_proto_marketdata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_marketdata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_marketdata_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_internal_proto_marketdata_proto protoreflect.FileDescriptor

const file_internal_proto_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/marketdata.proto\x12\n" +
	"marketdata\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\x0fGetPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\x92\x01\n" +
	"\x10GetPriceResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"]\n" +
	"\x13StreamPricesRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12,\n" +
	"\x12update_interval_ms\x18\x02 \x01(\x05R\x10updateIntervalMs\"\xe3\x01\n" +
	"\vPriceUpdate\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12<\n" +
	"\vchange_info\x18\x06 \x01(\v2\x1b.marketdata.PriceChangeInfoR\n" +
	"changeInfo\"\xc2\x01\n" +
	"\x0fPriceChangeInfo\x12#\n" +
	"\rchange_amount\x18\x01 \x01(\x01R\fchangeAmount\x12+\n" +
	"\x11change_percentage\x18\x02 \x01(\x01R\x10changePercentage\x12\x1d\n" +
	"\n" +
	"daily_high\x18\x03 \x01(\x01R\tdailyHigh\x12\x1b\n" +
	"\tdaily_low\x18\x04 \x01(\x01R\bdailyLow\x12!\n" +
	"\fdaily_volume\x18\x05 \x01(\x01R\vdailyVolume\"\xa4\x02\n" +
	"\x11SimulationRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12C\n" +
	"\x0fsimulation_type\x18\x04 \x01(\x0e2\x1a.marketdata.SimulationTypeR\x0esimulationType\x12@\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2 .marketdata.SimulationParametersR\n" +
	"parameters\"\xa0\x02\n" +
	"\x12SimulationResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12?\n" +
	"\x0fhistorical_data\x18\x02 \x03(\v2\x16.marketdata.PricePointR\x0ehistoricalData\x12=\n" +
	"\x0esimulated_data\x18\x03 \x03(\v2\x16.marketdata.PricePointR\rsimulatedData\x12M\n" +
	"\x12similarity_metrics\x18\x04 \x01(\v2\x1e.marketdata.StatisticalMetricsR\x11similarityMetrics\x12#\n" +
	"\rsimulation_id\x18\x05 \x01(\tR\fsimulationId\"\x8e\x02\n" +
	"\x0fScenarioRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12=\n" +
	"\rscenario_type\x18\x02 \x01(\x0e2\x18.marketdata.ScenarioTypeR\fscenarioType\x12>\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x1e.marketdata.ScenarioParametersR\n" +
	"parameters\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\"\xae\x01\n" +
	"\n" +
	"PricePoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\"\x9e\x02\n" +
	"\x12StatisticalMetrics\x127\n" +
	"\x17correlation_coefficient\x18\x01 \x01(\x01R\x16correlationCoefficient\x123\n" +
	"\x15volatility_similarity\x18\x02 \x01(\x01R\x14volatilitySimilarity\x12D\n" +
	"\x1ereturn_distribution_similarity\x18\x03 \x01(\x01R\x1creturnDistributionSimilarity\x12)\n" +
	"\x10trend_similarity\x18\x04 \x01(\x01R\x0ftrendSimilarity\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x01R\x0fconfidenceScore\"\xcd\x01\n" +
	"\x14SimulationParameters\x12+\n" +
	"\x11volatility_factor\x18\x01 \x01(\x01R\x10volatilityFactor\x12!\n" +
	"\ftrend_factor\x18\x02 \x01(\x01R\vtrendFactor\x12\x1f\n" +
	"\vdata_points\x18\x03 \x01(\x05R\n" +
	"dataPoints\x12#\n" +
	"\rinclude_noise\x18\x04 \x01(\bR\fincludeNoise\x12\x1f\n" +
	"\vnoise_level\x18\x05 \x01(\x01R\n" +
	"noiseLevel\"\xb3\x01\n" +
	"\x12ScenarioParameters\x12\x1c\n" +
	"\tintensity\x18\x01 \x01(\x01R\tintensity\x12'\n" +
	"\x0fduration_factor\x18\x02 \x01(\x01R\x0edurationFactor\x12'\n" +
	"\x0frecovery_factor\x18\x03 \x01(\x01R\x0erecoveryFactor\x12-\n" +
	"\x12gradual_transition\x18\x04 \x01(\bR\x11gradualTransition\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x9f\x02\n" +
	"\x13HealthCheckResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.marketdata.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12F\n" +
	"\adetails\x18\x04 \x03(\v2,.marketdata.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*{\n" +
	"\x0eSimulationType\x12\x1a\n" +
	"\x16STATISTICAL_SIMILARITY\x10\x00\x12\x0f\n" +
	"\vMONTE_CARLO\x10\x01\x12\x13\n" +
	"\x0fBROWNIAN_MOTION\x10\x02\x12\x12\n" +
	"\x0eMEAN_REVERSION\x10\x03\x12\x13\n" +
	"\x0fTREND_FOLLOWING\x10\x04*q\n" +
	"\fScenarioType\x12\t\n" +
	"\x05RALLY\x10\x00\x12\t\n" +
	"\x05CRASH\x10\x01\x12\x0e\n" +
	"\n" +
	"DIVERGENCE\x10\x02\x12\x12\n" +
	"\x0eMEAN_REVERTING\x10\x03\x12\x14\n" +
	"\x10VOLATILITY_SPIKE\x10\x04\x12\x11\n" +
	"\rCONSOLIDATION\x10\x05*N\n" +
	"\fHealthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032\x95\x03\n" +
	"\x11MarketDataService\x12E\n" +
	"\bGetPrice\x12\x1b.marketdata.GetPriceRequest\x1a\x1c.marketdata.GetPriceResponse\x12J\n" +
	"\fStreamPrices\x12\x1f.marketdata.StreamPricesRequest\x1a\x17.marketdata.PriceUpdate0\x01\x12S\n" +
	"\x12GenerateSimulation\x12\x1d.marketdata.SimulationRequest\x1a\x1e.marketdata.SimulationResponse\x12H\n" +
	"\x0eStreamScenario\x12\x1b.marketdata.ScenarioRequest\x1a\x17.marketdata.PriceUpdate0\x01\x12N\n" +
	"\vHealthCheck\x12\x1e.marketdata.HealthCheckRequest\x1a\x1f.marketdata.HealthCheckResponseBUZSgithub.com/quantfidential/trading-ecosystem/market-data-simulator-go/internal/protob\x06proto3"

var (
	file_internal_proto_marketdata_proto_rawDescOnce sync.Once
	file_internal_proto_marketdata_proto_rawDescData []byte
)

func file_internal_proto_marketdata_proto_rawDescGZIP() []byte {
	file_internal_proto_marketdata_proto_rawDescOnce.Do(func() {
		file_internal_proto_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_marketdata_proto_rawDesc), len(file_internal_proto_marketdata_proto_rawDesc)))
	})
	return file_internal_proto_marketdata_proto_rawDescData
}

var file_internal_proto_marketdata_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_proto_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_proto_marketdata_proto_goTypes = []any{
	(SimulationType)(0),          // 0: marketdata.SimulationType
	(ScenarioType)(0),            // 1: marketdata.ScenarioType
	(HealthStatus)(0),            // 2: marketdata.HealthStatus
	(*GetPriceRequest)(nil),      // 3: marketdata.GetPriceRequest
	(*GetPriceResponse)(nil),     // 4: marketdata.GetPriceResponse
	(*StreamPricesRequest)(nil),  // 5: marketdata.StreamPricesRequest
	(*PriceUpdate)(nil),          // 6: marketdata.PriceUpdate
	(*PriceChangeInfo)(nil),      // 7: marketdata.PriceChangeInfo
	(*SimulationRequest)(nil),    // 8: marketdata.SimulationRequest
	(*SimulationResponse)(nil),   // 9: marketdata.SimulationResponse
	(*ScenarioRequest)(nil),      // 10: marketdata.ScenarioRequest
	(*PricePoint)(nil),           // 11: marketdata.PricePoint
	(*StatisticalMetrics)(nil),   // 12: marketdata.StatisticalMetrics
	(*SimulationParameters)(nil), // 13: marketdata.SimulationParameters
	(*ScenarioParameters)(nil),   // 14: marketdata.ScenarioParameters
	(*HealthCheckRequest)(nil),   // 15: marketdata.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 16: marketdata.HealthCheckResponse
	nil,                          // 17: marketdata.HealthCheckResponse.DetailsEntry
	(*timestamp.Timestamp)(nil),  // 18: google.protobuf.Timestamp
}
var file_internal_proto_marketdata_proto_depIdxs = []int32{
	18, // 0: marketdata.GetPriceResponse.timestamp:type_name -> google.protobuf.Timestamp
	18, // 1: marketdata.PriceUpdate.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 2: marketdata.PriceUpdate.change_info:type_name -> marketdata.PriceChangeInfo
	18, // 3: marketdata.SimulationRequest.start_time:type_name -> google.protobuf.Timestamp
	18, // 4: marketdata.SimulationRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 5: marketdata.SimulationRequest.simulation_type:type_name -> marketdata.SimulationType
	13, // 6: marketdata.SimulationRequest.parameters:type_name -> marketdata.SimulationParameters
	11, // 7: marketdata.SimulationResponse.historical_data:type_name -> marketdata.PricePoint
	11, // 8: marketdata.SimulationResponse.simulated_data:type_name -> marketdata.PricePoint
	12, // 9: marketdata.SimulationResponse.similarity_metrics:type_name -> marketdata.StatisticalMetrics
	1,  // 10: marketdata.ScenarioRequest.scenario_type:type_name -> marketdata.ScenarioType
	14, // 11: marketdata.ScenarioRequest.parameters:type_name -> marketdata.ScenarioParameters
	18, // 12: marketdata.ScenarioRequest.start_time:type_name -> google.protobuf.Timestamp
	18, // 13: marketdata.PricePoint.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 14: marketdata.HealthCheckResponse.status:type_name -> marketdata.HealthStatus
	18, // 15: marketdata.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	17, // 16: marketdata.HealthCheckResponse.details:type_name -> marketdata.HealthCheckResponse.DetailsEntry
	3,  // 17: marketdata.MarketDataService.GetPrice:input_type -> marketdata.GetPriceRequest
	5,  // 18: marketdata.MarketDataService.StreamPrices:input_type -> marketdata.StreamPricesRequest
	8,  // 19: marketdata.MarketDataService.GenerateSimulation:input_type -> marketdata.SimulationRequest
	10, // 20: marketdata.MarketDataService.StreamScenario:input_type -> marketdata.ScenarioRequest
	15, // 21: marketdata.MarketDataService.HealthCheck:input_type -> marketdata.HealthCheckRequest
	4,  // 22: marketdata.MarketDataService.GetPrice:output_type -> marketdata.GetPriceResponse
	6,  // 23: marketdata.MarketDataService.StreamPrices:output_type -> marketdata.PriceUpdate
	9,  // 24: marketdata.MarketDataService.GenerateSimulation:output_type -> marketdata.SimulationResponse
	6,  // 25: marketdata.MarketDataService.StreamScenario:output_type -> marketdata.PriceUpdate
	16, // 26: marketdata.MarketDataService.HealthCheck:output_type -> marketdata.HealthCheckResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_proto_marketdata_proto_init() }
func file_internal_proto_marketdata_proto_init() {
	if File_internal_proto_marketdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_marketdata_proto_rawDesc), len(file_internal_proto_marketdata_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_marketdata_proto_goTypes,
		DependencyIndexes: file_internal_proto_marketdata_proto_depIdxs,
		EnumInfos:         file_internal_proto_marketdata_proto_enumTypes,
		MessageInfos:      file_internal_proto_marketdata_proto_msgTypes,
	}.Build()
	File_internal_proto_marketdata_proto = out.File
	file_internal_proto_marketdata_proto_goTypes = nil
	file_internal_proto_marketdata_proto_depIdxs = nil
}
